#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");
entry("pwd");
entry("send");
entry("shutdown");
entry("reboot");
entry("kill_child");
entry("recv");
entry("shmget");
entry("shmat");
entry("readavail");
entry("gpu_flush");
entry("gpu_flush_rect");
entry("yield");
entry("shmdt");
entry("flush_console");
entry("procinfo");
entry("stat");
entry("time");
entry("netping");
entry("netpoll");
entry("socket");
entry("sockbind");
entry("sendto");
entry("recvfrom");
entry("sockclose");
entry("tcpsocket");
entry("tcpconnect");
entry("tcpsend");
entry("tcprecv");
entry("tcpclose");

